# Generated by Django 3.2 on 2021-06-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('optiona', models.TextField()),
                ('optionb', models.TextField()),
                ('optionc', models.TextField()),
                ('optiond', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
