# Generated by Django 3.2 on 2021-06-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizid', models.AutoField(primary_key=True, serialize=False)),
                ('countofque', models.IntegerField()),
                ('questions', models.ManyToManyField(to='NewApp.Question')),
            ],
        ),
    ]
